-- ============================================================================
-- Config/Props.lua - 竞拍道具配置
-- ============================================================================

local Props = {}

-- 道具效果类型
Props.EFFECT = {
    SHOW_RARITY_CELL_COUNT     = "show_rarity_cell_count",      -- 显示指定品质物品的总格数
    SHOW_RARITY_ITEM_COUNT     = "show_rarity_item_count",      -- 显示指定品质物品的总数量
    SHOW_RANDOM_SILHOUETTE     = "show_random_silhouette",      -- 随机显示N件物品轮廓
    SHOW_SIZE_AVG_VALUE        = "show_size_avg_value",         -- 显示指定占位格数物品的平均价值
    SHOW_RANDOM_ITEM_INFO      = "show_random_item_info",       -- 随机显示一件物品的信息
    SHOW_RARITY_AVG_VALUE      = "show_rarity_avg_value",       -- 显示指定品质物品的总/均价值
    SHOW_RARITY_AVG_CELL_COUNT   = "show_rarity_avg_cell_count",   -- 显示指定品质物品的平均格数
    SHOW_RANDOM_ITEM_INFO_MULTI  = "show_random_item_info_multi",  -- 随机显示N件物品的完整信息
    SHOW_TOP_RARITY_SILHOUETTE   = "show_top_rarity_silhouette",   -- 显示最高品质物品的轮廓
    SHOW_LARGEST_ITEM_SILHOUETTE = "show_largest_item_silhouette", -- 显示占格最多物品的轮廓
    SHOW_CATEGORY_SILHOUETTE     = "show_category_silhouette",     -- 显示指定品类物品的轮廓/品质
    -- ── 新增（紫色高阶） ──
    SHOW_TOTAL_ITEM_COUNT      = "show_total_item_count",       -- 显示仓库所有物品总数
    SHOW_RANDOM_QUALITY_MULTI  = "show_random_quality_multi",   -- 随机显示N件物品的品质（L2_hint）
    SHOW_LARGEST_ITEM_INFO     = "show_largest_item_info",      -- 显示占格最多物品的完整信息
    SHOW_TOP_RARITY_ITEM_VALUE = "show_top_rarity_item_value",  -- 随机显示一件最高品质物品的价值
    -- ── 新增（金色高阶） ──
    SHOW_TOTAL_CELL_COUNT      = "show_total_cell_count",       -- 显示所有物品的总格数
    SHOW_RED_ITEM_SILHOUETTE   = "show_red_item_silhouette",    -- 显示所有红色物品的轮廓（L1）
    SHOW_TOP_N_LARGEST_INFO    = "show_top_n_largest_info",     -- 显示前N件大件物品的完整信息（L4）
    SHOW_TOP_RARITY_FULL_INFO  = "show_top_rarity_full_info",   -- 随机显示一件最高品质物品的完整信息（L4）
    -- ── 新增（红色极品） ──
    SHOW_RANDOM_N_ITEMS             = "show_random_n_items",              -- 随机显示N个物品完整信息
    SHOW_ALL_ITEM_QUALITY           = "show_all_item_quality",            -- 显示所有物品的品质
    SHOW_RED_ITEM_TOTAL_VALUE       = "show_red_item_total_value",        -- 显示所有红色物品的总价值
    SHOW_ALL_ITEMS                  = "show_all_items",                   -- 显示所有物品完整信息
    SHOW_ALL_ITEM_TOTAL_VALUE       = "show_all_item_total_value",        -- 显示所有物品的总价值
    -- SHOW_CATEGORY_SILHOUETTE 已在上方定义
}

-- 道具列表（按品质从低到高排序：白→绿→蓝→紫→红）
Props.LIST = {
    -- ── 白色品质 ──────────────────────────────
    {
        id = "scout_white_green_cells",
        name = "初级鉴定仪",
        desc = "显示所有绿色和白色品质物品的总格数",
        icon = "📦",
        iconImage = "image/prop_geo_01_20260515201141.png",
        effectType = Props.EFFECT.SHOW_RARITY_CELL_COUNT,
        effectParams = { rarities = { "white", "green" } },
        price = 1500,         -- 白色品质
        tier = "white",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "scout_green_count",
        name = "绿品探测器",
        desc = "显示所有绿色品质物品的总数量",
        icon = "🔍",
        iconImage = "image/prop_geo_02_20260515201156.png",
        effectType = Props.EFFECT.SHOW_RARITY_ITEM_COUNT,
        effectParams = { rarities = { "green" } },
        price = 1500,         -- 白色品质
        tier = "white",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "random_item_info",
        name = "物品侦察仪",
        desc = "随机显示一件物品的信息",
        icon = "🔎",
        iconImage = "image/prop_geo_03_20260515201255.png",
        effectType = Props.EFFECT.SHOW_RANDOM_ITEM_INFO,
        effectParams = {},
        price = 1500,         -- 白色品质
        tier = "white",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "xray_2_silhouette",
        name = "轮廓探测器",
        desc = "随机显示两件物品的轮廓",
        icon = "👁️",
        iconImage = "image/prop_geo_04_20260515201138.png",
        effectType = Props.EFFECT.SHOW_RANDOM_SILHOUETTE,
        effectParams = { count = 2 },
        price = 1500,         -- 白色品质
        tier = "white",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "appraise_green_value",
        name = "绿品估价仪",
        desc = "显示绿色品质物品的价值",
        icon = "💚",
        iconImage = "image/prop_geo_05_20260515201136.png",
        effectType = Props.EFFECT.SHOW_RARITY_AVG_VALUE,
        effectParams = { rarity = "green" },
        price = 1500,         -- 白色品质
        tier = "white",
        maxStack = 99,
        inGame = true,
    },
    -- ── 绿色品质 ──────────────────────────────
    {
        id = "xray_4_silhouette",
        name = "透视镜",
        desc = "随机显示4件物品轮廓",
        icon = "👁️",
        iconImage = "image/prop_geo_06_20260515201345.png",
        effectType = Props.EFFECT.SHOW_RANDOM_SILHOUETTE,
        effectParams = { count = 4 },
        price = 2500,         -- 绿色品质
        tier = "green",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "scout_blue_cells",
        name = "中级鉴定仪",
        desc = "显示所有蓝色品质物品的总格数",
        icon = "📊",
        iconImage = "image/prop_geo_07_20260515201144.png",
        effectType = Props.EFFECT.SHOW_RARITY_CELL_COUNT,
        effectParams = { rarities = { "blue" } },
        price = 2500,         -- 绿色品质
        tier = "green",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "dual_item_reveal",
        name = "双重侦察仪",
        desc = "随机显示两件物品的完整信息",
        icon = "🔭",
        iconImage = "image/prop_geo_09_20260516195128.png",
        effectType = Props.EFFECT.SHOW_RANDOM_ITEM_INFO_MULTI,
        effectParams = { count = 2 },
        price = 2500,         -- 绿色品质
        tier = "green",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "avg_cell_blue",
        name = "蓝品格数仪",
        desc = "显示蓝色品质物品的平均格数",
        icon = "📐",
        iconImage = "image/prop_geo_10_20260516200521.png",
        effectType = Props.EFFECT.SHOW_RARITY_AVG_CELL_COUNT,
        effectParams = { rarities = { "blue" } },
        price = 2500,         -- 绿色品质
        tier = "green",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "avg_cell_purple",
        name = "紫品格数仪",
        desc = "显示紫色品质物品的平均格数",
        icon = "📏",
        iconImage = "image/prop_geo_11_20260516195657.png",
        effectType = Props.EFFECT.SHOW_RARITY_AVG_CELL_COUNT,
        effectParams = { rarities = { "purple" } },
        price = 2500,         -- 绿色品质
        tier = "green",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "avg_cell_white_green",
        name = "低品格数仪",
        desc = "显示白色和绿色品质物品的平均格数",
        icon = "📋",
        iconImage = "image/prop_geo_12_20260516195707.png",
        effectType = Props.EFFECT.SHOW_RARITY_AVG_CELL_COUNT,
        effectParams = { rarities = { "white", "green" } },
        price = 2500,         -- 绿色品质
        tier = "green",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "total_value_green",
        name = "绿品总价仪",
        desc = "显示绿色品质物品的总价值",
        icon = "💰",
        iconImage = "image/prop_geo_13_20260516195658.png",
        effectType = Props.EFFECT.SHOW_RARITY_AVG_VALUE,
        effectParams = { rarity = "green", showTotalOnly = true },
        price = 2500,         -- 绿色品质
        tier = "green",
        maxStack = 99,
        inGame = true,
    },
    -- ── 蓝色品质（每日商店）──────────────────────────────
    {
        id = "top_rarity_silhouette",
        name = "极品探测仪",
        desc = "显示仓库中最高品质物品的轮廓",
        icon = "🔭",
        iconImage = "image/prop_geo_14_20260516212237.png",
        effectType = Props.EFFECT.SHOW_TOP_RARITY_SILHOUETTE,
        effectParams = {},
        price = 8000,
        tier = "blue",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "largest_item_silhouette",
        name = "大件透视仪",
        desc = "显示仓库中占格最多的物品的轮廓",
        icon = "📐",
        iconImage = "image/prop_geo_15_20260516212038.png",
        effectType = Props.EFFECT.SHOW_LARGEST_ITEM_SILHOUETTE,
        effectParams = {},
        price = 8000,
        tier = "blue",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "purple_total_value",
        name = "紫品估值仪",
        desc = "显示仓库中紫色品质物品的总价值",
        icon = "💜",
        iconImage = "image/prop_geo_16_20260516212040.png",
        effectType = Props.EFFECT.SHOW_RARITY_AVG_VALUE,
        effectParams = { rarity = "purple", showTotalOnly = true },
        price = 8000,
        tier = "blue",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    -- ── 蓝色品质（每日商店）- 品类透视镜 ──────────────────────────────
    {
        id = "cat_silhouette_antique",
        name = "古董透视镜",
        desc = "显示仓库中所有古董品类物品的轮廓",
        icon = "🏺",
        iconImage = "image/prop_cat_antique.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "antique", categoryName = "古董" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    {
        id = "cat_silhouette_daily",
        name = "日用透视镜",
        desc = "显示仓库中所有日用品类物品的轮廓",
        icon = "🧴",
        iconImage = "image/prop_cat_daily.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "daily", categoryName = "日用" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    {
        id = "cat_silhouette_energy",
        name = "能源透视镜",
        desc = "显示仓库中所有能源品类物品的轮廓",
        icon = "⚡",
        iconImage = "image/prop_cat_energy.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "energy", categoryName = "能源" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    {
        id = "cat_silhouette_transport",
        name = "交通透视镜",
        desc = "显示仓库中所有交通品类物品的轮廓",
        icon = "🚗",
        iconImage = "image/prop_cat_transport.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "transport", categoryName = "交通" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    {
        id = "cat_silhouette_tech",
        name = "科技透视镜",
        desc = "显示仓库中所有科技品类物品的轮廓",
        icon = "💻",
        iconImage = "image/prop_cat_tech.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "tech", categoryName = "科技" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    {
        id = "cat_silhouette_art",
        name = "艺术透视镜",
        desc = "显示仓库中所有艺术品类物品的轮廓",
        icon = "🎨",
        iconImage = "image/prop_cat_art.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "art", categoryName = "艺术" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    {
        id = "cat_silhouette_jewel",
        name = "珠宝透视镜",
        desc = "显示仓库中所有珠宝品类物品的轮廓",
        icon = "💎",
        iconImage = "image/prop_cat_jewel.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "jewel", categoryName = "珠宝" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    {
        id = "cat_silhouette_mechanical",
        name = "机械透视镜",
        desc = "显示仓库中所有机械品类物品的轮廓",
        icon = "⚙️",
        iconImage = "image/prop_cat_mechanical.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "mechanical", categoryName = "机械" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    {
        id = "cat_silhouette_fashion",
        name = "服饰透视镜",
        desc = "显示仓库中所有服饰品类物品的轮廓",
        icon = "👗",
        iconImage = "image/prop_cat_fashion.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "fashion", categoryName = "服饰" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    {
        id = "cat_silhouette_biotech",
        name = "医疗透视镜",
        desc = "显示仓库中所有医疗品类物品的轮廓",
        icon = "🧬",
        iconImage = "image/prop_cat_biotech.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { categoryId = "biotech", categoryName = "医疗" },
        price = 8000, tier = "blue", dailyLimit = 1, maxStack = 99, dailyShop = true, inGame = true,
    },
    -- ── 紫色品质（每日商店）──────────────────────────────
    {
        id = "appraise_4cell_value",
        name = "大件估价器",
        desc = "显示占位4格物品的平均价值",
        icon = "💎",
        iconImage = "image/prop_geo_08_new_20260515204523.png",
        effectType = Props.EFFECT.SHOW_SIZE_AVG_VALUE,
        effectParams = { cellCount = 4 },
        price = 30000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "gold_rarity_cell_count",
        name = "金品占格仪",
        desc = "显示仓库中所有金色品质物品的总格数",
        icon = "🟨",
        iconImage = "image/prop_geo_17_20260516212039.png",
        effectType = Props.EFFECT.SHOW_RARITY_CELL_COUNT,
        effectParams = { rarities = { "gold" } },
        price = 30000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "gold_rarity_item_count",
        name = "金品计数仪",
        desc = "显示仓库中所有金色品质物品的总数量",
        icon = "🏅",
        iconImage = "image/prop_geo_17_20260516212039.png",
        effectType = Props.EFFECT.SHOW_RARITY_ITEM_COUNT,
        effectParams = { rarities = { "gold" } },
        price = 30000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "gold_rarity_avg_cell_count",
        name = "金品格数仪",
        desc = "显示仓库中金色品质物品的平均格数",
        icon = "📊",
        iconImage = "image/prop_geo_17_20260516212039.png",
        effectType = Props.EFFECT.SHOW_RARITY_AVG_CELL_COUNT,
        effectParams = { rarities = { "gold" } },
        price = 30000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "gold_rarity_total_value",
        name = "金品估值仪",
        desc = "显示仓库中所有金色品质物品的总价值",
        icon = "💛",
        iconImage = "image/prop_geo_17_20260516212039.png",
        effectType = Props.EFFECT.SHOW_RARITY_AVG_VALUE,
        effectParams = { rarity = "gold", showTotalOnly = true },
        price = 30000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    -- ── 紫色品质（高阶，30k~120k）──────────────────────────────
    {
        id = "total_item_count",
        name = "总量计数仪",
        desc = "显示仓库中所有物品的总数量",
        icon = "🔢",
        iconImage = "image/prop_geo_17_20260516212039.png",
        effectType = Props.EFFECT.SHOW_TOTAL_ITEM_COUNT,
        effectParams = {},
        price = 30000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "size_avg_value_1",
        name = "一格均价仪",
        desc = "显示仓库中所有占1格物品的平均价值",
        icon = "1️⃣",
        iconImage = "image/prop_geo_08_new_20260515204523.png",
        effectType = Props.EFFECT.SHOW_SIZE_AVG_VALUE,
        effectParams = { cellCount = 1 },
        price = 30000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "size_avg_value_2",
        name = "二格均价仪",
        desc = "显示仓库中所有占2格物品的平均价值",
        icon = "2️⃣",
        iconImage = "image/prop_geo_08_new_20260515204523.png",
        effectType = Props.EFFECT.SHOW_SIZE_AVG_VALUE,
        effectParams = { cellCount = 2 },
        price = 40000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "size_avg_value_3",
        name = "三格均价仪",
        desc = "显示仓库中所有占3格物品的平均价值",
        icon = "3️⃣",
        iconImage = "image/prop_geo_08_new_20260515204523.png",
        effectType = Props.EFFECT.SHOW_SIZE_AVG_VALUE,
        effectParams = { cellCount = 3 },
        price = 50000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "size_avg_value_4",
        name = "四格均价仪",
        desc = "显示仓库中所有占4格物品的平均价值",
        icon = "4️⃣",
        iconImage = "image/prop_geo_08_new_20260515204523.png",
        effectType = Props.EFFECT.SHOW_SIZE_AVG_VALUE,
        effectParams = { cellCount = 4 },
        price = 55000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "top_rarity_item_value",
        name = "极品估价仪",
        desc = "随机显示一件最高品质物品的价值",
        icon = "🏆",
        iconImage = "image/prop_geo_14_20260516212237.png",
        effectType = Props.EFFECT.SHOW_TOP_RARITY_ITEM_VALUE,
        effectParams = {},
        price = 55000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "size_avg_value_5",
        name = "五格均价仪",
        desc = "显示仓库中所有占5格物品的平均价值",
        icon = "5️⃣",
        iconImage = "image/prop_geo_08_new_20260515204523.png",
        effectType = Props.EFFECT.SHOW_SIZE_AVG_VALUE,
        effectParams = { cellCount = 5 },
        price = 65000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "size_avg_value_6",
        name = "六格均价仪",
        desc = "显示仓库中所有占6格物品的平均价值",
        icon = "6️⃣",
        iconImage = "image/prop_geo_08_new_20260515204523.png",
        effectType = Props.EFFECT.SHOW_SIZE_AVG_VALUE,
        effectParams = { cellCount = 6 },
        price = 70000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "random_quality_8",
        name = "八重侦察仪",
        desc = "随机显示8件物品的品质",
        icon = "🔮",
        iconImage = "image/prop_geo_09_20260516195128.png",
        effectType = Props.EFFECT.SHOW_RANDOM_QUALITY_MULTI,
        effectParams = { count = 8 },
        price = 75000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "quad_item_reveal",
        name = "四重侦察仪",
        desc = "随机显示4件物品的完整信息",
        icon = "🔭",
        iconImage = "image/prop_geo_09_20260516195128.png",
        effectType = Props.EFFECT.SHOW_RANDOM_ITEM_INFO_MULTI,
        effectParams = { count = 4 },
        price = 85000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "random_quality_10",
        name = "十重侦察仪",
        desc = "随机显示10件物品的品质",
        icon = "💠",
        iconImage = "image/prop_geo_09_20260516195128.png",
        effectType = Props.EFFECT.SHOW_RANDOM_QUALITY_MULTI,
        effectParams = { count = 10 },
        price = 100000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "largest_item_info",
        name = "重器鉴定仪",
        desc = "显示仓库中占格最多的物品的完整信息",
        icon = "🔬",
        iconImage = "image/prop_geo_15_20260516212038.png",
        effectType = Props.EFFECT.SHOW_LARGEST_ITEM_INFO,
        effectParams = {},
        price = 120000,
        tier = "purple",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    -- ── 金色品质（每日商店，15万~42万；商城 20~50 点券）──────────────────────────────
    {
        id = "red_item_count",
        name = "红品探测仪",
        desc = "显示仓库中红色品质物品的总数量",
        icon = "🔴",
        iconImage = "image/prop_geo_02_20260515201156.png",
        effectType = Props.EFFECT.SHOW_RARITY_ITEM_COUNT,
        effectParams = { rarities = { "red" } },
        price = 150000,
        mallPrice = 20,
        tier = "gold",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "total_cell_count",
        name = "总格计数仪",
        desc = "显示仓库中所有物品的总格数",
        icon = "🔢",
        iconImage = "image/prop_geo_07_20260515201144.png",
        effectType = Props.EFFECT.SHOW_TOTAL_CELL_COUNT,
        effectParams = {},
        price = 160000,
        mallPrice = 22,
        tier = "gold",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "red_item_cells",
        name = "红品总格仪",
        desc = "显示仓库中红色品质物品的总格数",
        icon = "🔲",
        iconImage = "image/prop_geo_01_20260515201141.png",
        effectType = Props.EFFECT.SHOW_RARITY_CELL_COUNT,
        effectParams = { rarities = { "red" } },
        price = 180000,
        mallPrice = 25,
        tier = "gold",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "red_item_avg_cells",
        name = "红品均格仪",
        desc = "显示仓库中红色品质物品的平均格数",
        icon = "📐",
        iconImage = "image/prop_geo_10_20260516200521.png",
        effectType = Props.EFFECT.SHOW_RARITY_AVG_CELL_COUNT,
        effectParams = { rarities = { "red" } },
        price = 210000,
        mallPrice = 28,
        tier = "gold",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "red_item_silhouette",
        name = "红品轮廓仪",
        desc = "显示仓库中所有红色品质物品的轮廓",
        icon = "👁️",
        iconImage = "image/prop_geo_04_20260515201138.png",
        effectType = Props.EFFECT.SHOW_RED_ITEM_SILHOUETTE,
        effectParams = {},
        price = 300000,
        mallPrice = 35,
        tier = "gold",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "top3_largest_info",
        name = "重器揭秘仪",
        desc = "显示仓库中占格最多的前3件物品的完整信息",
        icon = "🔬",
        iconImage = "image/prop_geo_15_20260516212038.png",
        effectType = Props.EFFECT.SHOW_TOP_N_LARGEST_INFO,
        effectParams = { topN = 3 },
        price = 350000,
        mallPrice = 40,
        tier = "gold",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "fifteen_quality_scan",
        name = "十五重侦察仪",
        desc = "随机显示15件物品的品质",
        icon = "💠",
        iconImage = "image/prop_geo_09_20260516195128.png",
        effectType = Props.EFFECT.SHOW_RANDOM_QUALITY_MULTI,
        effectParams = { count = 15 },
        price = 380000,
        mallPrice = 45,
        tier = "gold",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    {
        id = "top_rarity_full_info",
        name = "极品鉴定仪",
        desc = "随机显示一件最高品质物品的完整信息",
        icon = "👑",
        iconImage = "image/prop_geo_14_20260516212237.png",
        effectType = Props.EFFECT.SHOW_TOP_RARITY_FULL_INFO,
        effectParams = {},
        price = 420000,
        mallPrice = 50,
        tier = "gold",
        dailyLimit = 1,
        maxStack = 99,
        inGame = true,
        dailyShop = true,
    },
    -- ── 红色品质（商城专供，40~100 点券）──────────────────────────────
    -- 通用6件
    {
        id = "red_random_8",
        name = "八品透视仪",
        desc = "随机揭示仓库中8件物品的完整信息",
        icon = "🎲",
        iconImage = "image/prop_geo_09_20260516195128.png",
        effectType = Props.EFFECT.SHOW_RANDOM_N_ITEMS,
        effectParams = { count = 8 },
        mallPrice = 40,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_random_10",
        name = "十品透视仪",
        desc = "随机揭示仓库中10件物品的完整信息",
        icon = "🎰",
        iconImage = "image/prop_geo_10_20260516200521.png",
        effectType = Props.EFFECT.SHOW_RANDOM_N_ITEMS,
        effectParams = { count = 10 },
        mallPrice = 50,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_all_quality",
        name = "万品品质仪",
        desc = "显示仓库中所有物品的品质等级（不含详细价值）",
        icon = "🌈",
        iconImage = "image/prop_geo_11_20260516195657.png",
        effectType = Props.EFFECT.SHOW_ALL_ITEM_QUALITY,
        effectParams = {},
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_red_total_value",
        name = "赤品总价仪",
        desc = "显示仓库中所有红色品质物品的累计估值总额",
        icon = "💰",
        iconImage = "image/prop_geo_12_20260516195707.png",
        effectType = Props.EFFECT.SHOW_RED_ITEM_TOTAL_VALUE,
        effectParams = {},
        mallPrice = 70,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_all_items",
        name = "万物透视仪",
        desc = "揭示仓库中全部物品的完整信息，一览无余",
        icon = "👁️",
        iconImage = "image/prop_geo_13_20260516195658.png",
        effectType = Props.EFFECT.SHOW_ALL_ITEMS,
        effectParams = {},
        mallPrice = 90,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_all_total_value",
        name = "万物总价仪",
        desc = "显示仓库中所有物品的累计估值总额",
        icon = "📈",
        iconImage = "image/prop_geo_17_20260516212039.png",
        effectType = Props.EFFECT.SHOW_ALL_ITEM_TOTAL_VALUE,
        effectParams = {},
        mallPrice = 80,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    -- 品类轮廓10件（每个品类一件，揭示该品类物品的轮廓和品质）
    {
        id = "red_cat_energy",
        name = "能源轮廓仪",
        desc = "揭示仓库中能源品类物品的轮廓形状与品质等级",
        icon = "⚡",
        iconImage = "image/prop_cat_energy_20260516212755.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "energy" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_cat_transport",
        name = "交通轮廓仪",
        desc = "揭示仓库中交通品类物品的轮廓形状与品质等级",
        icon = "🚗",
        iconImage = "image/prop_cat_transport_20260516212753.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "transport" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_cat_art",
        name = "艺术轮廓仪",
        desc = "揭示仓库中艺术品类物品的轮廓形状与品质等级",
        icon = "🎨",
        iconImage = "image/prop_cat_art_20260516212752.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "art" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_cat_tech",
        name = "科技轮廓仪",
        desc = "揭示仓库中科技品类物品的轮廓形状与品质等级",
        icon = "💻",
        iconImage = "image/prop_cat_tech_20260516213148.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "tech" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_cat_antique",
        name = "古董轮廓仪",
        desc = "揭示仓库中古董品类物品的轮廓形状与品质等级",
        icon = "🏺",
        iconImage = "image/prop_cat_antique_20260516212945.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "antique" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_cat_jewel",
        name = "珠宝轮廓仪",
        desc = "揭示仓库中珠宝品类物品的轮廓形状与品质等级",
        icon = "💎",
        iconImage = "image/prop_cat_jewel_20260516212939.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "jewel" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_cat_mechanical",
        name = "机械轮廓仪",
        desc = "揭示仓库中机械品类物品的轮廓形状与品质等级",
        icon = "⚙️",
        iconImage = "image/prop_cat_mechanical_20260516212754.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "mechanical" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_cat_daily",
        name = "日用轮廓仪",
        desc = "揭示仓库中日用品类物品的轮廓形状与品质等级",
        icon = "🏠",
        iconImage = "image/prop_cat_daily_20260516212751.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "daily" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_cat_fashion",
        name = "服饰轮廓仪",
        desc = "揭示仓库中服饰品类物品的轮廓形状与品质等级",
        icon = "👗",
        iconImage = "image/prop_cat_fashion_20260516213206.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "fashion" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
    {
        id = "red_cat_biotech",
        name = "医疗轮廓仪",
        desc = "揭示仓库中医疗品类物品的轮廓形状与品质等级",
        icon = "🏥",
        iconImage = "image/prop_cat_biotech_20260516212951.png",
        effectType = Props.EFFECT.SHOW_CATEGORY_SILHOUETTE,
        effectParams = { category = "biotech" },
        mallPrice = 60,
        tier = "red",
        maxStack = 99,
        inGame = true,
    },
}

-- 按 id 索引
Props.BY_ID = {}
for _, item in ipairs(Props.LIST) do
    Props.BY_ID[item.id] = item
end

return Props
